language: java
jdk: openjdk-13
sudo: false
before_install: chmod +x gradlew

script:
  - ./gradlew build
#  - ./gradlew check
#  - ./gradlew codeCoverageReport

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
